services:
  mysqldb:
    image: mysql:8.0.34
    volumes: 
      - mysql_data:/var/lib/mysql
      - ./ms-patient/database/data.sql:/docker-entrypoint-initdb.d/data.sql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: medilabo_solutions
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: app_user
      MYSQL_PASSWORD: rootroot

  mongodb:
    images: mongo:5.0
    volumes:
      - mongodb_data:/var/lib/mongodb
      - ./ms-notes/database/init-db.js:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_DATABASE: MediLaboSolutions
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: rootroot

  ms-patient:
    image: ms-patient
    depends_on:
      - mysqldb
    restart: always
    ports:
      - '8081:8081'
    environment:
      MYSQL_URL: jdbc:mysql://mysqldb:3306/medilabo_solutions?serverTimezone=UTC
      MYSQL_USER: app_user
      MYSQL_PASSWORD: rootroot
      MYSQL_PORT: '3307'

  ms-notes:
    image: ms-notes
    depends_on:
      - mongodb
    restart: always
    ports: '8082:8082'
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: '27017'
      MONGO_DATABASE: MediLaboSolutions
      MONGO_USERNAME: root
      MONGO_PASSWORD: rootroot

volumes: 
  mysql_data: { }
  mongodb_data: { }