services:
  mysqldb:
    image: mysql:8.0.34
    volumes: 
      - mysql_data:/var/lib/mysql
      - ./ms-patient/database/data.sql:/docker-entrypoint-initdb.d/data.sql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: medilabo_solutions
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: app_user
      MYSQL_PASSWORD: rootroot
    networks:
      - medilabosolution-app

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_DATABASE: MediLaboSolutions
    networks:
      - medilabosolution-app

  ms-patient:
    image: ms-patient
    container_name: ms-patient
    depends_on:
      - mysqldb
    restart: always
    ports:
      - '8081:8081'
    environment:
      MYSQL_URL: jdbc:mysql://mysqldb:3306/medilabo_solutions?serverTimezone=UTC
      MYSQL_USER: app_user
      MYSQL_PASSWORD: rootroot
      MYSQL_PORT: '3307'
    networks:
      - medilabosolution-app

  ms-notes:
    image: ms-notes
    container_name: ms-notes
    depends_on:
      - mongodb
    restart: always
    ports: 
      - '8082:8082'
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: '27017'
      MONGO_DATABASE: MediLaboSolutions
    networks:
      - medilabosolution-app

  ms-diabetes-report:
    image: ms-diabetes-report
    container_name: ms-diabetes-report
    depends_on:
      - ms-patient
      - ms-notes
    restart: always
    ports:
      - '8083:8083'
    networks:
      - medilabosolution-app

  ms-gateway:
    image: ms-gateway
    container_name: ms-gateway
    depends_on:
      - ms-patient
      - ms-notes
      - ms-diabetes-report
    restart: always
    ports:
    - '8080:8080'
    networks:
      - medilabosolution-app

  frontend:
    image: angular-frontend
    container_name: angular-frontend
    depends_on:
      - ms-patient
      - ms-notes
      - ms-diabetes-report
      - ms-gateway
    restart: always
    ports:
      - '4200:4200'
    networks:
      - medilabosolution-app

volumes: 
  mysql_data: { }
  mongodb_data: 

networks:
  medilabosolution-app:
    driver: bridge