spring.application.name=ms-api-gateway

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/medilabo_solutions?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootroot

spring.cloud.gateway.routes[0].id=ms-patient
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/patients/**