spring.application.name=ms-api-gateway
spring.main.web-application-type=reactive

server.port=8080
server.address=0.0.0.0

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


security.jwt.secret=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

spring.cloud.gateway.routes[0].id=ms-patient
spring.cloud.gateway.routes[0].uri=http://ms-patient:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/patient/**

spring.cloud.gateway.routes[1].id=ms-notes
spring.cloud.gateway.routes[1].uri=http://ms-notes:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/notes/**

spring.cloud.gateway.routes[2].id=ms-diabetes-report
spring.cloud.gateway.routes[2].uri=http://ms-diabetes-report:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/diabetes-report/**