spring.application.name=ms-api-gateway
spring.main.web-application-type=reactive
server.port=8080
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


security.jwt.secret=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

spring.cloud.gateway.routes[0].id=ms-patient
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/**
